[project]
name = 'Blockchain-Based-Environmental-Ecosystem-Restoration'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.baseline-assessment]
path = 'contracts/baseline-assessment.clar'
clarity_version = 2
epoch = 2.5

[contracts.outcome-verification]
path = 'contracts/outcome-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
